### ISSUE TITLE
gethostbyname is deprecated

### ISSUE THREAD

**Issue by mattiaverga** [XEphem/XEphem#62]
GUI/xephem/netmenu.c calls the deprecated function `gethostbyname()` which needs to be replaced by `getaddrinfo()`.

**Comment by dcecchino** [comment]
some thoughts are some of us use older unix workstations and like to have that type of compatibility, i run xephem on hpux10.20

**Comment by brandon-rhodes** [comment]
@mattiaverga — Do we have examples at this point of systems where XEphem isn't compiling or is giving runtime errors because of its use of the old routine? My guess is that until it actually starts breaking XEphem, we should keep the old call in place for the reason cited by @dcecchino.

**Comment by rmathar** [comment]
gethostbyname() will be unable to resolve IPv6 addresses. So the problem will evolve at the speed that IPv6 becomes reality. See https://twiki.cern.ch/twiki/pub/EGEE/IPv6FollowUp/Introduction_to_IPv6_programming_C_Java_PHP_perl.pdf |
https://security.stackexchange.com/questions/121344/why-gethosbyname-is-as-bad-as-gets-by-design |
https://blog.erratasec.com/2015/01/you-shouldnt-be-using-gethostbyname.html |
https://github.com/FreeRDP/FreeRDP/issues/4147 |
https://apidock.com/ruby/v2_5_5/Socket/gethostbyname/class |
https://docs.freebsd.org/en/books/developers-handbook/ipv6/
Someone on a HP-UX 10.20 (of 1996?) could try *man getaddrinfo* so detect if that library was already present on that system. HP-UX 11.00 has getaddrinfo(3) man pages.

**Comment by brandon-rhodes** [comment]
> gethostbyname() will be unable to resolve IPv6 addresses. So the problem will evolve at the speed that IPv6 becomes reality.

Ah, thank you for pointing that out—so, we can imagine, XEphem will first experience a failure when one of the astronomy data servers it needs to contact ceases to advertise an IPv4 address and becomes an IPv6-only service.

I will hazard the guess that we are at least 10 years away from public-facing servers from leading institutions dropping their final IPv4 address and going IPv6-only. For example, by long tradition, I see if I'm on the Internet by typing `host mit.edu` (because they have a short and easy-to-type hostname) and its current response is:

```
$ host mit.edu
mit.edu has address 104.122.75.84
mit.edu has IPv6 address 2600:1408:7400:195::255e
mit.edu has IPv6 address 2600:1408:7400:1a2::255e
mit.edu mail is handled by 100 mit-edu.mail.protection.outlook.com.
```

They are currently running with addresses available for both IP versions. On the day (if it comes) that they drop the v4 address, old systems will no longer be able to contact a server named `mit.edu`. And so with all the hostnames that XEphem contacts—we have until they drop their final v4 address before this becomes a user-visible failure.

To keep supporting old systems as long as we can, while keeping the code as simple as we can, let's keep `gethostbyname()` up til the moment it stops working for a specific host that XEphem needs. At that point, we can re-open this issue and work out a change.

But I welcome a pull request if someone (@mattiaverga?) knows of a way, maybe with a simple `#ifdef` or two, to go ahead start using `getaddrinfo()` on modern systems while still using `gethostbyname()` on older systems. As UNIX is rarely that convenient, though—often system capabilities are not cleanly advertised in a way that `#ifdef` can detect—I'll understand completely if now is not the time to put together a pull request like that.

Thanks again for the nudge towards modern system calls, @mattiaverga, but XEphem wants to keep supporting old systems for as long as possible—per the emails I receive, there are quite a few beautiful old UNIX workstations in the world whose sole remaining use is to run XEphem. It would be a shame for old SGI machines to finally face the recycler because we pulled the plug on them.
