### ISSUE TITLE
GUI too small on high DPI monitor

### ISSUE THREAD

**Issue by Geremia** [XEphem/XEphem#91]
How do I scale the GUI up so it's not microscopic on high DPI monitors?

**Comment by pidloop** [comment]
XEphem can't but generally the X Server has an option to scale pixels 2x2.
At least that's true on my 5k display running macOS and XQuartz.

**Comment by Geremia** [comment]
@pidloop How do I "scale pixels 2x2"?

**Comment by pidloop** [comment]
2x2 is the default already so I haven't had to mess with it. I think you can use xrandr to change resolutions.

**Comment by pidloop** [comment]
I played a bit and although xrandr does work, changing the size always engages rootfull mode, so you loose the normal macOS desktop. 

But then I found an even easier way: just set the desired DPI in the xquartz resources. For example to expand everything 2x more:

`defaults write org.xquartz.X11 dpi 192
`

be sure xquartz is not running when you do this.

**Comment by dave-kaye** [comment]
XEphem has a semi-easy method for resizing the GUI.  The window size is automatically adjusted based upon the font sizes displayed.  Increasing the font size will increase the GUI size. This is a two step process.

1) From the main menu, select **Preferences>>Fonts**. The font selection menu appears, containing a search bar and search results. Selecting any font in the results box will provide a visual demonstration of the font on the bottom of the window. A group of four radio buttons is at the top of the window. Select the "_Set_" action. The top menu has entries for _Buttons, Text and Other_. Select a category and the drop down menu displays the items in that category. Selecting any of the items will set that item to the font you have chosen. You will want to set all of the items to a larger font size, each one individually. You can mix/match fonts as you desire.

2) Once you have set the fonts, you must save the selections.  From the main menu, select **Preferences>>Save**. Select both major and minor preferences and press the "_Save now_" button.

Further information on these two functions can be found in the Help/Reference Manual.

Note: It is stated that sometimes XEphem will not immediately resize all of the windows properly after these steps, but that restarting XEphem will resize the windows correctly.  It also would be prudent to restart XEphem before changing the font size, since in saving the preferences you may accidentally save a setting you were unaware of changing.

**Comment by Geremia** [comment]
@dave-kaye  Thank you, but is there a way to do this faster, such as by editing a preference file?

**Comment by dave-kaye** [comment]
There is a file in the user directory, but it will take longer to edit it because until you change a font, the item does not exist in the file.  So you must type the name of the item then the new font.

The original instructions are actually much easier than it seems.  Once you have selected a font from the search window and pressed "set" radio button, it is extremely rapid.  Just chose the top menu item, then the submenu item and click.  Then just repeat the process.  Takes about 5 seconds per item.  I did the whole system in less than 30 seconds once I had my font.  And if you don't like the result, there is a "return to default" in the radio button array - just repeat the main/submenu process or go to your xephem user directory (for me it is home>.xephem) and edit the format file because now it will have the font items in it.

**Comment by Geremia** [comment]
@dave-kaye  This helped. I made my `~/.xephem/XEphem`:
```
XEphem*XmCascadeButton.fontList:             -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmCascadeButtonGadget.fontList:       -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmLabel.fontList:                     -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmLabelGadget.fontList:               -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmList.fontList:                      -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmPushButton.fontList:                -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmPushButtonGadget.fontList:          -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmScale.fontList:                     -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmTextField.fontList:                 -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmToggleButton.fontList:              -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem*XmToggleButtonGadget.fontList:        -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem.AnnoFont:                             *-lucidatypewriter*medium*-20-*-iso8859-1
XEphem.CnsFont:                              *-helvetica-medium-r-*-20-*-iso8859-1
XEphem.SkyGridFont:                          *-helvetica-medium-r-*-20-*-iso8859-1
XEphem.cursorTrackingFont:                   *-helvetica-medium-r-*-20-*-iso8859-1
XEphem.tipFont:                              -b&h-lucidatypewriter-medium-r-normal-sans-20-140-100-100-m-120-iso8859-1
XEphem.viewsFont:                            *-helvetica-medium-r-*-20-*-iso8859-1
XEphem.viewsGreekFont:                       *-helvetica-medium-r-*-20-*-iso8859-1
```
Basically, I changed `*-10-*` to `*-20-*`, doubling the font size.
